name: shogi
description: A simple shogi engine for Dart and Flutter. This engine can be combined with `flutter_shogi_board` to render static game board positions, tsume problems or shogi castles.
version: 0.0.3
homepage: https://github.com/defuncart/shogi

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.6

dev_dependencies:
  test: ^1.15.0
